### ISSUE TITLE
Checkbox select for multi item actions (such as downloading CVs)

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#10]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/11/checkbox-select-for-multi-item-actions

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul does it mean that in search results there would be checkboxes near every item, and then button Download at the bottom?  

Could you also list other "multi item actions", cause I see only Download button while testing.

**Comment by Samyoul** [comment]
>@Samyoul does it mean that in search results there would be checkboxes near every item, and then button Download at the bottom?

Yes this is correct.

> Could you also list other "multi item actions", cause I see only Download button while testing.

Good point, in the current version there isn't but there will be other functions a user can do with a result. Issue https://github.com/Samyoul/dywaj-issues/issues/24 is one of these actions.

**Comment by PovilasKorop** [comment]
@Samyoul problem: Could you provide an instruction on how to work with your checkboxes? You have them customized from default browser behaviour. As I copied over the checkbox syntax from permission.blade.php file but it still shows an empty square no matter if I press it or not.

**Comment by Samyoul** [comment]
Could you push your branch to the repo and I'll see if I can spot what the problem is.

**Comment by Samyoul** [comment]
@PovilasKorop Are you testing your code? You seem to be introducing a number of bugs that would be easily spotted by testing the code works.

**Comment by PovilasKorop** [comment]
@Samyoul will push checkboxes code tomorrow. As I mentioned, I'm having trouble uploading different files to the different feature branches - so locally it works but when I create another branch it messes up with the old local master, probably I don't have enough experience with branching like this - I was used to create bigger features, then merging, and then branching again. Or have a separate develop branch which is constantly updated. We could possibly change the workflow if we continue in the future? 

If I introduced bugs unrelated to that, sorry, could you give an example? Will be more careful in the future and do more testing.

**Comment by Samyoul** [comment]
>We could possibly change the workflow if we continue in the future?

Yes, that's fine. We can have a milestone branch like you suggest. `Or have a separate develop branch which is constantly updated.`

> If I introduced bugs unrelated to that, sorry, could you give an example? Will be more careful in the future and do more testing.

I deleted that last comment, because I'm not certain the bugs are caused by you or by me when resolving merge conflicts. When I commit the fixes I'll link it here for you to see.

**Comment by PovilasKorop** [comment]
@Samyoul While doing the checkbox part for file downloads I ran into a bit of an approach issue. At this moment your system is only capable of downloading 1 file at a time with reducing the user credits. This is fine, but as we need to download multiple files, we have few options:  

1. Make the Download selected Cvs button open a new window and download each file one by one until user runs out of credits (it would still open windows even if they did). - This one is one of the worst approaches in my opinion.

2. Make that button send an Ajax request to server and ask for a bulk download (zip all files from the s3 locally and download the zip file) and if the amount of selected files is greater than the amount of downloads available - we would simply show the message and don't download anything at all.

3. Make that button summon a popup which would list all of the selected cvs, then do a check of how much tickets user has and continue downloading files one by one while displaying the process.

(option 2 and 3 seems more logical and looks like a better approach)
Which way of download seems the best for you? Maybe you have a vision yourself of how this should really work?

**Comment by Samyoul** [comment]
I had a different approach in mind, but suggestion 3 seems like better approach. Let's proceed with :

>Make that button summon a popup which would list all of the selected cvs, then do a check of how much tickets user has and continue downloading files one by one while displaying the process.
