### ISSUE TITLE
Save Search Criteria for future use.

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#11]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/12/save-search-criteria-for-future-use

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul need more details - should there be a new menu item with list of saved criteria sets? Or only the last one is saved? And then probably a button "Repeat search with these criteria"?

**Comment by Samyoul** [comment]
## Process Flow:

### Saving search criteria
- User submits a new search:
- Application returns results:

![cv search results](https://cloud.githubusercontent.com/assets/5702426/23075664/3d4156ae-f535-11e6-9cd1-d1250ce83131.png)

- User clicks new "Save Search Criteria" button.
- Application saves the search criteria submitted by the user into a new DB table. Returns user back to previous search page, gives flash message on success.

### Viewing saved search criteria:
