### ISSUE TITLE
Adjustable Results Per Page

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#12]
Add a pre-set select input so that the user can choose the number of items per page that they would prefer.

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/13/increase-results-per-page-to-20

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul should that be a dropdown for every search (default 100 items per page) or stored somewhere in user's profile for future use every time?

**Comment by Samyoul** [comment]
> @Samyoul should that be a dropdown for every search (default 100 items per page) or stored somewhere in user's profile for future use every time?

Yes, a select input element containing preset numbers (10, 15, 20, 30 , 40, 50, 100), default is 10. Have the option in an advanced search div, that is hidden by default.

`cv-search/submit`
![cv search submit](https://cloud.githubusercontent.com/assets/5702426/23075370/14e20ea2-f534-11e6-840b-be099ea3877a.png)


Additionally as you rightly suggest, have a setting in the user's profile to set their own personal default figure, this should be any integer the user chooses.

**Comment by PovilasKorop** [comment]
@Samyoul you're saying "have a setting in the user's profile" - Do we need to make the profile edit or there is one existing? So far I found just the view page of my profile.

**Comment by Samyoul** [comment]
>@Samyoul you're saying "have a setting in the user's profile" - Do we need to make the profile edit or there is one existing? So far I found just the view page of my profile.

Add an option under settings

![user dashboard](https://cloud.githubusercontent.com/assets/5702426/23168094/d0557568-f83e-11e6-8a43-4f6ce5ad9fa4.png)
