### ISSUE TITLE
Change result score from percentage to plain floating point number

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#13]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/14/change-result-score-from-percentage-to

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul what should be the logic of that floating point number? 
For example, "Relevance Score : 109.87 %" should be turned to what?

And is that only in viewing the results or somewhere deeper in the algorithm?

**Comment by Samyoul** [comment]
If you view the code: (https://github.com/Samyoul/dywaj-user-interface/blob/master/resources/views/cv-search/result.blade.php#L36 ) We talk the raw floating point figure and format it into a percentage. You basically need to perform the super simple task of removing the formatting echoing only the raw number.
