### ISSUE TITLE
Result line items to have alternate background colours

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#14]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/15/result-line-items-to-have-alternate

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul could you give more details - what alternate backgrounds exactly and how they should look/work?

**Comment by Samyoul** [comment]
Something like this:

![cv search results](https://cloud.githubusercontent.com/assets/5702426/23074845/28328a38-f532-11e6-87b1-1bce7441db2d.png)
