### ISSUE TITLE
Create User Dashboard

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#16]
**NOTE:** Most of this is completed

This dashboard will be the universal dashboard for all users.

Currently the user roles are:

* ~~Super Admin~~
* ~~Admin~~
* ~~Customer~~
* Candidate

User dashboards should show:

* ~~**Customer dashboard** - must have a user profile, and CV search functionality~~
* **Candidate dashboard** - must have user profile
* ~~**Admin dashboard** - must have admin profile, customer list, candidate list and CV search functionality~~
* ~~**Super Admin** - must have admin and super admin list, role and permission assignment plus all other admin abilities.~~

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/22/create-user-dashboard

created an issue 2016-07-08

**Comment by PovilasKorop** [comment]
@Samyoul do you have any mockup or view what exactly that candidate dashboard should look and what information about user profile should be shown? In what way? This description is pretty vague.

**Comment by Samyoul** [comment]
Please see here : https://wireframe.cc/3RRMow

Candidate can choose to make

- location,
- specific contact details (phone numbers, address and email),
- current job title
- expected salary

public or private.

**Comment by PovilasKorop** [comment]
@Samyoul 

I have made the layout but some questions popped out:

- Photo will have to be uploaded via profile edit page or somewhere else?
- Links to cv - simply download the CV from the s3 bucket or you want to do something different? This also leads to the question who will be able to see this page as we currently prepared it as a simple "Your public profile preview page".
- Details hiding: We have a location above the toggle box and inside it, is it different field or just a miss type? (same goes for expected salary and current job title). Or this is where I should add the toggle (not in the profile edit page as checkbox'es)?

All in all, these questions are the remaining bits before I push the system to your side.

**Comment by PovilasKorop** [comment]
@Samyoul And finally it looks like the address field is missing at this moment, should I add it as I did with the Bio or is it not needed now?

**Comment by Samyoul** [comment]
>Photo will have to be uploaded via profile edit page or somewhere else?

Yes this is correct. I think it would be too much to ask for during user signup.

>Links to cv - simply download the CV from the s3 bucket or you want to do something different?

No, definitely not a direct download from S3. See the functionality for CV download on CV search. We pass the request for download through a controller which then relays the CV to the user. CV download from a user profile will count as a CV download against the CV download token bucket.

>This also leads to the question who will be able to see this page as we currently prepared it as a simple "Your public profile preview page".

Make the candidate profile public but redact all hideable data ( _location, specific contact details, current job title, expected salary_ ).

>Details hiding: We have a location above the toggle box and inside it, is it different field or just a miss type? (same goes for expected salary and current job title). Or this is where I should add the toggle (not in the profile edit page as checkbox'es)?

The toggle box on the wireframe ( https://wireframe.cc/3RRMow ) is actually just a note, to let you know that certain fields ( _location, specific contact details, current job title, expected salary_ ) should be hideable.
