### ISSUE TITLE
 Candidate User Profile

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#17]
1. View that shows all information we have about the candidate.
1. Name, address, phone, email, CVs we assume are theirs, CVs we know are theirs (because they uploaded them).
1. Edit ability any of the static data, by the candidate user.
1. Ability to add CVs, update CVs and add multiple concurrent CVs. For multiple concurrent CVs allow the user to name the CVs to distinguish them.

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/23/candidate-user-profile

created an issue 2016-07-08

**Comment by PovilasKorop** [comment]
@Samyoul a few questions:  

1. Number (3): what do you mean by "any of the static data"? Same fields as in (2)?

2. Add/update CVs - how should it work: is it just uploading the files, or some text processing in them, could you describe the current procedure, maybe it works already somehow? How do you get / add / process CVs currently?

**Comment by Samyoul** [comment]
>Number (3): what do you mean by "any of the static data"? Same fields as in (2)?

Sorry yes you are correct, same as in (2), "static" is a poor choice of words in this context.

>Add/update CVs - how should it work: is it just uploading the files, or some text processing in them, could you describe the current procedure, maybe it works already somehow? How do you get / add / process CVs currently?

Currently there isn't any CV upload functionality for this application. The CVs that currently exist were purchased in a massive bulk and then processed using Python.

I think we should keep the Python processing separate from the user interface of the system.

**The process:**

There are two database tables that will help with this functionality.
[*files*](https://github.com/Samyoul/dywaj-user-interface/blob/master/database/migrations/2016_05_31_124125_create_files_table.php)
[*cvs*](https://github.com/Samyoul/dywaj-user-interface/blob/master/database/migrations/2016_05_31_124048_create_cvs_table.php)

We will also need to set 2 new .envs

`NEW_CV_PREFIX` - The prefix where new cvs are stored by php right after upload
`INDEXED_CV_PREFIX` - The prefix where cvs are moved to by Python after indexing

- File is uploaded to server
- Application generates data to save in the **files** table:
    - **candidate_id** the ID of the candidate uploading the file.
    - the **object_key** ( `timestamp ('%Y-%m-%d-%H-%M-%S') + '_' + uuid4() + '_'  + original_file_name`, for UUID v4 see https://github.com/ramsey/uuid )
    - **storage_service** ( this will be S3 )
    - **storage_location** ( the S3 bucket name )
    - **original_name** (the original name of the file)
    - **extension**
- Application generates data to be saved in the **cvs** table:
    - **candidate_id** the ID of the candidate uploading the file.
    - **file_id** the ID of the file created above
    - **indexed** is set to `0` . The Python side of the system will handle the indexing of the data.
- Application moves the file to S3 storage (`NEW_CV_PREFIX ."\". $file->object_key`)

**Comment by PovilasKorop** [comment]
@Samyoul thank you for such detailed explanation. The only unclear bit: the fresh uploaded CV must be indexed by us (in the elastic search) or it will be done without our interaction?

**Comment by Samyoul** [comment]
The application will store the new CV in the S3 storage, this is the last thing that the user interface part of application needs to do.

When the CV is added to the`'NEW_CV_PREFIX` in the S3 bucket it is added to the Python indexer's queue for processing.

**Comment by PovilasKorop** [comment]
@Samyoul How should I treat the destroy of the CV? Is there anything specific you have in mind that I would need to do or you don't want the delete at all?

**Comment by PovilasKorop** [comment]
@Samyoul And as of this task, I only added a bulk upload (prototype: http://prntscr.com/ei93pw) where user will press add new button and get a new row for CV upload. When he selects a file - we will auto fill the title field with the file name so that the user would be able to change the file name if the wants to. Is this ok with you?

And I don't really see an edit/show logic (of course, you just upload your cv and that is it for the edit) so I got the idea that they are not even needed there, am I right?

**Comment by Samyoul** [comment]
>How should I treat the destroy of the CV? Is there anything specific you have in mind that I would need to do or you don't want the delete at all?

At moment we will keep the CVs never deleting them. Perhaps in the future we will archive them.

>And as of this task, I only added a bulk upload (prototype: http://prntscr.com/ei93pw) where user will press add new button and get a new row for CV upload. When he selects a file - we will auto fill the title field with the file name so that the user would be able to change the file name if the wants to. Is this ok with you?

Yes that is fine.The default number of CV upload rows shown should be 1.

>And I don't really see an edit/show logic (of course, you just upload your cv and that is it for the edit) so I got the idea that they are not even needed there, am I right?

Yes you are correct.
