### ISSUE TITLE
Candidate Ghost Profile Creation Functionality

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#18]
Because the system already holds data on a number of individuals based on extractions from CVs we can build a ghost profile for this individual.

**Important information** - Candidate accounts need a mechanism by which they can be claimed.

Claiming mechanism could work as follows:

assign new ghost candidate with a 512 bit auth token, and a boolean int denoting its 'claimed' status.

The auth token can be used in an email to validate the user's email exists. Email can be sent in two circumstances:

1) If the user receives a claiming email notice. This email will state that the user's CV is on our records but we'd like for them to log in and update it. The email would contain a link, using the auth code, that would automatically log the user in and show them the details we currently hold. The candidate is considered claimed at this point.

The user must set a password at this point. No further activity is permitted of the user until they set their password. The user will then be able to update their details, view their CV etc.

2) If the user attempts to log into the system or sign up to the system using the email address we have stored under an unclaimed candidate, we inform the user and send them an email asking for validation of their email address. This email will contain a link with the auth token code. The candidate is considered claimed at this point.

Once the user clicks the link, the user will be logged in and taken to their dashboard, and asked to set their password. No further activity is permitted of the user until they set their password. The user will then be able to update their details, view their CV etc.

**Process flow:**

* Loop through each CV we have on record.
* Use email address found in the CV as a means to identify a candidate.

* **If** we haven't seen the address previously create a new Candidate and assign to it a new user, assign the user the 'candidate' role. Some data will need to be extracted from the search index: DB Cv->File->object_key = ES Index documents.cv.id 
* **Else**, we find the Candidate using the email address

* Assign the CV to the Candidate.

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/24/candidate-ghost-profile-creation

created an issue 2016-07-08

**Comment by PovilasKorop** [comment]
@Samyoul started on this task, need your opinion.

**Performance:**

After running a basic prototype of the script, I have noticed that it does require quite a lot of time to run and resources.

The following time was needed to import ~50k CV entries to the system: 
Job done, time taken: 414.40940594673s (on my local Macbook Pro)

It varies a bit from time to time depending on system load but it is still quite a lot of time. So, question for this would be:

What machine are you going to run the script on and what is the time limit that you intend it to be? I am asking this only because at this point with rough calculations it would take about 3-4 hours to import all of the information with php and send the emails to the imported users.

Our second option would be to run this script on a language that can access more hardware resources, such as processors which would increase the efficiency of this script. Which means you would have to create such script from your side or by another developer.

Some of your CV does not have any assumed email in them, so I am ignoring them at this moment. Is that okay with you or we need to parse the content again to try to find an email? (this will increase the time needed to import).

And finally, what should I do with some random emails that your system provide, such as: -aimee.regan@hotmail.co.uk, ...garycole744@btinternet.com, as we could try to remove the - but the dots are required for most emails and some providers do allow to enter multiple dots in a row...

**Comment by Samyoul** [comment]
>What machine are you going to run the script on and what is the time limit that you intend it to be? I am asking this only because at this point with rough calculations it would take about 3-4 hours to import all of the information with php and send the emails to the imported users.

For a one off processing of 900,000 documents 3-4 hours is acceptable, however it will likely be less as we have a specialised server for this kind of thing. 

**Please Note:** The ghost account creation process **should not** include sending emails, this will be done separately via a system outside of the user interface.

>Some of your CV does not have any assumed email in them, so I am ignoring them at this moment. Is that okay with you or we need to parse the content again to try to find an email? (this will increase the time needed to import).

Yes ignore them.

>And finally, what should I do with some random emails that your system provide, such as: -aimee.regan@hotmail.co.uk, ...garycole744@btinternet.com, as we could try to remove the - but the dots are required for most emails and some providers do allow to enter multiple dots in a row...

The problem with these email addresses is that they technically are valid. However I take your point, that they don't look like valid email addresses. Perhaps we could trim any non-alpha numeric characters that prepend an email address. Something like `preg_match("/_*\W*/", $input_line, $output_array);` catches the cases you highlight.

The below example would probably work:

``` php
$email = "...-email.email@email.com"
preg_match("/_*\W*/", $email, $output_array);
$email = str_replace($output_array[0], "", $email, 1);
```

**Comment by PovilasKorop** [comment]
@Samyoul Committed a version of the importer.

This version create candidate entry and assigns him a cv. There is a file entry but it is a bit unclear of what the purpose of it is and how should it essentially work, so could you clarify the logic behind it for us to add it's support if it is needed?

**Comment by Samyoul** [comment]
@PovilasKorop 

>There is a file entry but it is a bit unclear of what the purpose of it is and how should it essentially work, so could you clarify the logic behind it for us to add it's support if it is needed?

Do you mean the `File` model ? https://github.com/Samyoul/dywaj-user-interface/blob/master/app/Models/File/File.php

**Comment by PovilasKorop** [comment]
@Samyoul yes, correct

**Comment by Samyoul** [comment]
Ok, if you look at the migrations for Files and CVs:

- https://github.com/Samyoul/dywaj-user-interface/blob/master/database/migrations/2016_05_31_124048_create_cvs_table.php
- https://github.com/Samyoul/dywaj-user-interface/blob/master/database/migrations/2016_05_31_124125_create_files_table.php

You will see that CVs have a File associated with them. The File's `object_key` field will be the same as `$results['docs'][*]['_id'];`.

In production the cvs and files tables have about 850,000+ rows. They each correspond to an entry in the Elasticsearch index and to an entry in the S3 bucket.

Note : https://github.com/Samyoul/dywaj-issues/issues/18#issue-198140893 

>If we haven't seen the address previously create a new Candidate and assign to it a new user, assign the user the 'candidate' role. Some data will need to be extracted from the search index: DB Cv->File->object_key = ES Index documents.cv.id

So we need to find the CV in the database and assign it to the candidate, instead of creating a new CV ( https://github.com/Samyoul/dywaj-user-interface/pull/16/files#diff-b9f0f88de953d8d4b09bd4846158fd75R145 ).

**Comment by PovilasKorop** [comment]
@Samyoul Ok, now I'm lost with this one,

As of this point I did the import to import the candidate to the **candidates** table and cv to the **cvs** table. I do not create any kind of user for the candidate as we intended to do a check when creating a user with registration form to see if there is a candidate with such email and if there is - connect both of them.

Now, after reading your latest messages it seems that I was not supposed to touch the **cvs** table except update and I had to work with **users** -> **candidates** -> **cvs** (just update candidate_id) -> **files**.

Could you try to clarify what I was supposed to import and where? 
ps. Maybe it would help if you would show some screenshots of your current database tables or some kind of schema as what I need to retrieve ant put in what table.

Thank you.

**Comment by Samyoul** [comment]
Your approach is fine, we just need to find the CV in the database and assign it to the candidate. You just need to update your code https://github.com/Samyoul/dywaj-user-interface/pull/16/files#diff-b9f0f88de953d8d4b09bd4846158fd75R125

The following code could do this:

``` php
private function createCandidate($cv)
{
    // Validate email
    if (! $cv['assumed_email'] || $cv['assumed_email'] == '') {
        $this->failedCvs[] = $cv;
        return;
    }

    // find or create candidate
    if (isset($this->createdUsers[$cv['assumed_email']])) {
        $user = $this->createdUsers[$cv['assumed_email']];
    } else {
        $user = Candidate::create([
            'user_id' => 0,
            'full_name' => $cv['name'],
            'email' => $cv['assumed_email'],
            'claimed' => 0,
            'auth_token' => $this->newToken()
        ]);
        $this->createdUsers[$cv['assumed_email']] = $user;
    }

    // Find the database file and its cv assign them both to the candidate.
    $file = File::where('object_key' => $doc['_id'])->first();
    $cv = $file->cv();

    $user->files()->save($file);
    $user->CVs()->save($cv);
}
```

I believe some of the Eloquent relationships need to be established for the above to work.

>Maybe it would help if you would show some screenshots of your current database tables or some kind of schema as what I need to retrieve ant put in what table.

I'll send you over a sample of the data in the production database.

**Comment by Samyoul** [comment]
**Files:**

SQL : https://gist.github.com/Samyoul/dd2b6e8d07d309bdb7d45358351dc7bc
CSV : https://gist.github.com/Samyoul/1f25cecd441c6cf68fe5f36ce3b3d43e

---

**CVs:**

SQL : https://gist.github.com/Samyoul/772e0cebf77bcd8cd8a858cbf5a91b17
CSV : https://gist.github.com/Samyoul/27cbd5eb0f429f45dc389d9929713a05

**Comment by PovilasKorop** [comment]
@Samyoul committed new code to pull request
