### ISSUE TITLE
Create Candidate Sign Up Page and functionality

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#19]
Details to follow for this.

Note there is a prototype that I will share the details of.

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/25/create-candidate-sign-up-page-and

created an issue 2016-07-08

**Comment by Samyoul** [comment]
Further details: https://bitbucket.org/Samyoul/job-board/commits/b28db4eaa04699fc814a1a894dce1e9d9ae18e82

TODO: Get a screenshot of this login, and add the code to a branch, reference the branch here.

**Comment by Samyoul** [comment]
Basically we are looking to emulate the registration process of https://www.reed.co.uk/account/register .

I've imported a little code from the old repository which may help some way. See here: https://github.com/Samyoul/dywaj-user-interface/commits/candidateAccount1.0

**Comment by PovilasKorop** [comment]
@Samyoul Made this registration process but I'm stuck at the claiming of existing candidate.
I would like to know a bit more details on how that claiming.

You have said that this will be done via different script for the invitation itself but how should I handle the invitation from registration point? You mentioned that it should re-send the email but if we don't have it, how can we send it? Or should I simply send them some kind of a text with the link once again?

**Comment by PovilasKorop** [comment]
@Samyoul pushed the changes so far, but not sure about branches again - before you merged previous pull request, I've branched from my develop branch, not sure how it will work from your side when testing.

**Comment by Samyoul** [comment]
Just keep pushing to a singe branch. You can merge and create pull requests multiple times from the same branch.
