### ISSUE TITLE
Can we have a option on the number of lines of highlight data shown

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#2]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/3/can-we-have-a-option-on-the-number-of

created an issue 2016-06-01

**Comment by PovilasKorop** [comment]
@Samyoul don't understand this one - is it the same as https://github.com/Samyoul/dywaj-issues/issues/12 ? Or "highlight data" is a different thing?

**Comment by Samyoul** [comment]
Ah, this is something that is specific to Elasticsearch. But you don't need to know very much, only what "Highlights" and "fragments" are, and they are very basic and easy to understand.

So "Highlight data" is a different thing to issue https://github.com/Samyoul/dywaj-issues/issues/12 .

See below:
![cv search results](https://cloud.githubusercontent.com/assets/5702426/23077464/89bcad38-f53c-11e6-8bcd-824316f900f9.png)

The 5 lines of text in the red box are Highlights. The current default is 5 maximum. Each line is called a "Fragment".

Please reference ( https://github.com/Samyoul/dywaj-user-interface/blob/master/app/Http/Controllers/CvSearchController.php#L146 )

You can set the maximum number of fragments, or lines of highlights, with the method call `$highlight->setNumberOfFragments(10)` .

The option to change the default number of highlight fragments should be an advance option, found in the hidden div.
