### ISSUE TITLE
Payment Service Provider

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#26]
https://github.com/Samyoul/dywaj-user-interface/commits/PaymentServiceProvider
https://developer.gocardless.com/getting-started/api/introduction/

Branch PaymentServiceProvider is basically a payment / subscription abstraction library that currently has only on method of payment, a direct debit provided called "GoCardless". There is also product access permission (called ServiceAccess ) management, along with subscription management.

**Work that needs to be done:**
Test and ensure GoCardless integration works and 
Integrate GoCardless WebHook functionality (webhooks are how GoCardless informs the application a payment was made.)
Restructure the relationship between User and access to services.

---

**Current inefficient relationship:**
User has one Customer.
Customer may have a Subscription
Customer may have many TokenBuckets
Subscriptions may have many TokenBuckets

Details on token buckets (https://en.wikipedia.org/wiki/Token_bucket) , I've also got working code implementation of the token bucket in the branch.

**Propose new relationship:**
User has one Customer
Customer has many ServiceAccesses
ServiceAccess may have a Subscription
ServiceAccess may have many TokenBuckets

The above relationship tree is too messy and doesn't work for subscriptions that allow the user to have access to multiple services that have multiple actions associated with them. Fundamentally the Customer / Subscription / Token Bucket relationship is one about access rights and permissions to / on a service.

If we use controller and middleware logic on a ServiceAccess model it would simplify the higher level permission check.

**ServiceAccess model:**
id
deal_id
customer_id
subscription_id (optional)
token_bucket_id (optional)

**Service model:**
id
name ['CV Download', 'Job Posting']

Service has many ServiceActions

**ServiceAction model:**
id
name ['Make CV Search', 'Make CV Download', 'Post Job']
service_id

ServiceAction belongs to a Service

**Deal model:**
id
price int (optional)
billing_frequency int (optional)
service_id
lifespan int (number of seconds) (optional)
public boolen

Deal has many DealActions

**DealAction model:**
id
deal_id
service_action_id
units_per_period
unit_refill_period

DealAction belongs to a Deal

It would be simpler to handle, if we limit one Deal to one Service

**Subscribing to a deal:**
Customer selects Deal, goes through subscription successfully.
A subscription has an end date if the deal has a price and a lifespan
If the Deal has no price no subscription is required
If the Deal has no units_per_period, no token bucket is required
A Service Access model is created
A Service Access model belongs to a Deal and to a Customer
A Service Access model may have a Subscription and may have a token bucket

**Checking Access:**
Check user->customer has service access to service.
AND user->customer->serviceAccess->deal->service->id == accessedServiceId
AND check Service Access has subscription, if so is the subscription active?

**Using Service Action:**
Check service access action has token bucket, if so attempt to take token, perform action.

**Comment by PovilasKorop** [comment]
@Samyoul ok after analysing deeper what's functioning and not, here are my comments/questions:

**Currently not working functions (built but with bugs):**
Subscription cancellation

**Currently not built function at all (has todo in code):**
Subscription change
History

**Questionable logic:** At the moment there is a hard-coded currency of GBP which would be ok but GoCardless has this schema: http://prntscr.com/emmu2i where only UK accepts GBP, SEPA zone has to get amount in EUR, Sweden has to get in SEK. http://prntscr.com/emn82i . So the question would be, what is your target users country? As at the moment you can't collect payments from these schemes/countries: http://prntscr.com/emmvhv (their support is coming but no information on how soon).

All in all, at the moment we do have a partially working subscription script which lets you create an account and pay for the service if you are from UK (your GoCardless account) or if you are from SEPA zone you charge in EUR (it has to be changed in code. Might need re-calculations for the conversion + euro zone needs VAT added at the moment which is not supported yet as far as I can see).

**Comment by Samyoul** [comment]
>At the moment there is a hard-coded currency of GBP which would be ok but GoCardless has this schema: http://prntscr.com/emmu2i where only UK accepts GBP, SEPA zone has to get amount in EUR, Sweden has to get in SEK. http://prntscr.com/emn82i . So the question would be, what is your target users country? 

Yes, for convenience I've hardcoded the currency to GBP. Currently the only target country is the UK.

Let me know if you need any further information.

**Comment by PovilasKorop** [comment]
@Samyoul ok a few more:  

1. I noticed that the Change subscription actually does not make much sense here, could you please give more details on what should be in there as at this moment you only subscribe and get the tokens.

2. Where should I put **history** there? (I guess that I should list all of subscriptions/cancellations there, right?)

**Comment by Samyoul** [comment]
>I noticed that the Change subscription actually does not make much sense here, could you please give more details on what should be in there as at this moment you only subscribe and get the tokens.

The subscriber will have access to a number of `Deals`, if the subscriber wishes to use subscribe to another `Deal` then they will need to change their subscription from the current one to the new one.

>Where should I put history there? (I guess that I should list all of subscriptions/cancellations there, right?)

Yes, but also most importantly their payment history.

**Comment by PovilasKorop** [comment]
@Samyoul For the change page, wouldn't it be better if user unsubscribes from current Deal and subscribes to another one? Or you want to display a list of deals on the change page to simply remove old service and give user a new one instead?

**Comment by Samyoul** [comment]
>For the change page, wouldn't it be better if user unsubscribes from current Deal and subscribes to another one? Or you want to display a list of deals on the change page to simply remove old service and give user a new one instead?

I think we should allow the user the ability to subscribe to multiple deals concurrently, some deal offer completely different things to each other. As you suggest a list of deals would be most helpful for the user to choose from. In that context I think you are correct that a user should have the option to unsubscribe and subscribe manually.

**Comment by PovilasKorop** [comment]
@Samyoul This is exactly as it works now, without the change button.

General progress update: 

1. Payments engine is still missing **History** and that needs investigation in GoCardless to see if they return payments date and etc.

2. As for the relationship of user access to services - this is still work in progress as I am attempting to minify refactoring costs by using Laravel features such as hasManyThrough. At the moment I added the missing ServiceAccess and tied it up to all of the token buckets, subscriptions and user.

**Comment by PovilasKorop** [comment]
@Samyoul committed the change but please don't use that commit yet - something's wrong with branches again and some files/code are missing in new commit. Will fix tomorrow.

**Comment by Samyoul** [comment]
@PovilasKorop Could you explain the process flow of this pull request?

What are deal types?
Why are billing frequencies managed?

**Comment by PovilasKorop** [comment]
@Samyoul To be honest, I haven't touched the logic behind them from your initial code that was stored in the repository. That part was done before me.

**Comment by Samyoul** [comment]
Partially resolved with https://github.com/Samyoul/dywaj-user-interface/pull/19

**Comment by Samyoul** [comment]
@PovilasKorop The next stage of developing the payment service provider is tying in the access rights.

From this issue's description:

>**Checking Access:**
Check user->customer has service access to service.
AND user->customer->serviceAccess->deal->service->id == accessedServiceId
AND check Service Access has subscription, if so is the subscription active?

>**Using Service Action:**
Check service access action has token bucket, if so attempt to take token, perform action.

I think that there may be a need to manage `Services` and `ServiceActions` in code rather than in the database because the only time another service or service action would be added to the system is when a developer would add it. We can use Enum model classes.

**Comment by PovilasKorop** [comment]
@Samyoul Ok after some more investigation - a few questions: 

1. At the moment you have a permission system based on **names** and **middlewares**. For example: middleware gets a name **search** and it looks if that user has the permission. So, I need to make it look not for search name but for specific **id** in that middleware? If so, will every single user have it? (at the moment it looks like that this applies to customers only).

2. Next thing you mentioned
_"I think that there may be a need to manage Services and ServiceActions in code rather than in the database because the only time another service or service action would be added to the system is when a developer would add it. We can use Enum model classes."_

So this means that I need to add configurable services which would then be assigned to deals, right? This would allow us to follow the check logic but it will require of re-doing all of the authorization engine.

All in all, I am a bit lost in this goal and what are you trying to do. As for example: if I were to leave the permissions as they are but just grant a specific service access to some parts of the system (such as for example **cv search**) if subscription is active and deny it if it is not. In this case I would not need to touch the existing permissions system and possibly break something but add checks at specific actions instead.

**Comment by Samyoul** [comment]
The current permissions system is very basic. Permissions are tied to the user roles. Access to services are limited by the number of tokens in the user's bucket.

We need to rewrite the authorisation engine for accessing services, because at the moment the current system is not very flexible and doesn't allow an admin user to create a deal that would allow varying accesses to the application.

Also as new services are added to the application we don't wont users to be able to access them just because their user role permits it, we need their permissions to be governed by what they are subscribed to.

The eventual goal is to create functionality that will allow an admin user they ability to create a Deal for specific services and service actions. So permissions will be based on the user's deals rather than the user's roles/role permissions.

**Comment by PovilasKorop** [comment]
@Samyoul ok then it seems like quite a big task - use Laravel ACL (roles/access/policies) then add your services/deals logic to those policies, and then assign that to specific functions in Dywaj.  

I guess I would need Vicki's permission on spending more time here, cause I'm not sure what is your budget for this (currently I work under hourly rate). Or your permission to continue is enough in this case?

**Comment by Samyoul** [comment]
@PovilasKorop Sorry for another late response, we've recently bought a new house and trying to juggle work around no internet and moving things and sorting the house. I will try to keep more on top of replying.

We've haven't really got a budget for this, we just need to get the application working in the way we need it to. My permission is enough, though if you want to send Vicki an estimation of cost that would be great.

Please proceed.

**Comment by PovilasKorop** [comment]
@Samyoul pushed the changes into a separate branch with pull request, see comments there.

**Comment by Samyoul** [comment]
Resolved with https://github.com/Samyoul/dywaj-user-interface/commit/764e465254a6fa06ef55d44528fa2f323a34f0a9
