### ISSUE TITLE
GoCardless Webhook Events

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#27]
Build out and complete the handling and support of GoCardless Event : https://developer.gocardless.com/api-reference/#core-endpoints-events

https://github.com/Samyoul/dywaj-user-interface/pull/19#issuecomment-294451008

### Events to develop for :

**Mandates**

https://developer.gocardless.com/api-reference/#events-mandate-actions

- `reinstated`
- `cancelled`
- `failed`
- `expired`
- `replaced`

If a customer's mandate has been cancelled, failed or expired stop access to the service unless they mandate has been replaced or reinstated.

**Payments**

https://developer.gocardless.com/api-reference/#events-payment-actions

- `confirmed`
- `cancelled`
- `failed`
- `charged_back`
- `chargeback_cancelled`
- `chargeback_settled`
- `resubmission_requested`

If a customer's payment has been confirmed allow them access to the service for 1 subscription period from the date of the payment, unless the payment has been cancelled or charged_back and the chargeback hasn't been cancelled.

Suspend the customer's access to their subscribed service if their payment failed, cancelled or was charged_back.

If resubmission is requested, display to the customer that payment failed and has been re-requested.

**Subscriptions**

https://developer.gocardless.com/api-reference/#events-subscription-actions

- `cancelled`
- `finished`

Suspend the customer's access to the service if the subscription has been cancelled or is finished.

**Comment by PovilasKorop** [comment]
@Samyoul I see this task is related, so should I work on it at the moment, or we're leaving webhooks to later? Or you will work on it? (or someone else)

**Comment by Samyoul** [comment]
This is a related task, but it is lower in priority verse https://github.com/Samyoul/dywaj-issues/issues/26#issuecomment-294454501 which is the next thing needs to be worked on.

**Comment by PovilasKorop** [comment]
@Samyoul ok started on this webhooks task. The problem with it is that it would take time even to set up the project somewhere on some staging server (to get URLs for webhooks - it won't work for local setup) and then analyze each status of webhook returned, which, as we haven't work with GoCardless before, will take long time.

So, __question 1__. Do you have any tips how to get quicker results? Have you worked with GoCardless before?

And __question 2__. Wouldn't it make more sense for you to do this task, if you have worked with this provider before and know all the details?

**Comment by PovilasKorop** [comment]
@Samyoul any update?

**Comment by Samyoul** [comment]
>So, question 1. Do you have any tips how to get quicker results? Have you worked with GoCardless before?

The only tips I can give, I have given, pointing out what needs to be focused on in the description of this issue.

I have not worked with GoCardless, aside from writing the basic interfacing for this project.

>And question 2. Wouldn't it make more sense for you to do this task, if you have worked with this provider before and know all the details?

No, I haven't worked with GoCardless before this project.

**Comment by PovilasKorop** [comment]
@samyoul thanks for the response. Then I think it would be better for you to hire someone who has worked with GoCardless instead of paying me hourly rate to try to guess how it works.

Related: while you did not respond, I've got a new big project. So even if you do want me to work on GoCardless, realistically I could go back on Dywaj in a few weeks or so.

Or should I raise this directly to Vicki?

**Comment by Samyoul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GoCardless Webhook Events #27](https://trello.com/c/fqmIDMQm/9-gocardless-webhook-events-27)

**Comment by Samyoul** [comment]
Resolved with https://github.com/Samyoul/dywaj-user-interface/commit/076634a43338305fda2c7c4dcbbe502590932890
