### ISSUE TITLE
 Add a change search criteria button

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#3]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/4/add-a-change-search-criteria-button

created an issue 2016-06-01

**Comment by PovilasKorop** [comment]
@Samyoul do I understand correctly - this button should be on results page and basically redirect to the search form with pre-filled values of current search? And then person would change something and search again. Correct?

**Comment by Samyoul** [comment]
>@Samyoul do I understand correctly - this button should be on results page and basically redirect to the search form with pre-filled values of current search? And then person would change something and search again. Correct?

Yes this is correct.
