### ISSUE TITLE
Add Candidate Sector Editing  Functionality

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#57]
>We also found that people are unsure how to edit the sectors on their profile, this is probably also linked to the emailing issue because when people sign up they are told that they are going to receive a confirmation email and they aren't taken straight to their account and therefore are unable to 'edit profile'.

**Comment by Samyoul** [comment]
@Nyanko-sensei 

>I didn't see in any menu link to <url>/user/edit/<customer_id>.
Should I add edit button in <url>/user/profile that links to <url>/user/edit/<customer_id> (Estimate: 15min)
>
>Or should user be redirected there, when they login first time (Estimate: 2h, would create migration to add flag "isNewUser" to user. After login, if "isNewUser" would redirect to <url>/user/edit/<customer_id>, and after clicking "update" set "isNewUser" flag to false)

---

The url is : `{url}/user/edit/{id}`

The issue is candidates can set their sector and sector roles at registration, but currently there is not any functionality to allow them to update their choices later.

**Comment by Nyanko-sensei** [comment]
current js code for sector and sector roles selection is in template blade file. Can I move that to separate js file, so, that code could be reused in different templates

**Comment by Samyoul** [comment]
@Nyanko-sensei 

Yes, this is fine.

**Comment by Nyanko-sensei** [comment]
I began moving js code, and have question. Seems like in this project there are 3 separate js coding styles:
global functions in separate files
global functions in template
angular

in which style you would prefer that I code js, and can and would it be better if I code js in model design pattern, or is global functions preferred way.

**Comment by Samyoul** [comment]
Yes, you are right, we have a number of approaches. I think that a model design pattern would be an improvement. We currently don't have an JS testing so, we could have tests written for each JS class that you write.

**Comment by Samyoul** [comment]
I've noticed that you've suggested the following route : `{url}/sector/edit/{user}`

I think it would make more sense for the route to be : `{url}/user/{id}/edit/sectors`
