### ISSUE TITLE
Admin Sector / Role CRUD Functionality.

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#58]
>There needs to be more sectors, I know I had mentioned previously about adding sports management etc. this still hasn't been added and there have been a few people that have come back saying "I don't think you're hiring in my industry".

**Comment by Nyanko-sensei** [comment]
@Samyoul  I have one question. Should we let delete and update roles and sectors which are selected by one or more users. And should we show how many users selected each sector/role?

**Comment by Samyoul** [comment]
@Nyanko-sensei This is a good question.

I agree with you that we should not delete or update roles and sectors which are owned by any users.

Yes, it would be a useful metric to see how many users have selected each sector/role.
