### ISSUE TITLE
Make Candidate Sector / Role Registration Selection Easier

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#59]
>Even though you have added the video to explain how to select more sectors, it seems people are still confused how to do this, I've had two people last week say "I wanted to select more industries but could only select one, how do I edit this?". Can this be made simpler so you can select the sectors one after another?

**Comment by Samyoul** [comment]
>Could you give url where this thing can be done, and link to video

**Comment by Nyanko-sensei** [comment]
ready for testing, pull request 28

**Comment by Samyoul** [comment]
Resolved with https://github.com/Samyoul/dywaj-user-interface/pull/28
