### ISSUE TITLE
Add Parallax sticky navigation to Home

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#61]
To make it easier for users we need to make is clear what is sign up and login.

**Comment by Samyoul** [comment]
**Start Position:**

![dywaj do you want a job](https://user-images.githubusercontent.com/5702426/35678771-7de313ee-074c-11e8-8366-bbcfac511661.png)

**End Position:**

Text slides out to the right. Button becomes smaller.

![dywaj do you want a job 1](https://user-images.githubusercontent.com/5702426/35678856-d9bb7878-074c-11e8-9bea-a2ad0663fbae.png)

**Comment by Samyoul** [comment]
@Nyanko-sensei Just making sure you've seen the above comment.

**Comment by Nyanko-sensei** [comment]
I think I get it now, will estimate that

**Comment by Samyoul** [comment]
Resolved with https://github.com/Samyoul/dywaj-user-interface/pull/35/commits/401bf862d748ba5b0be426c867118d2a18a2d5b8
