### ISSUE TITLE
 Search term predictive/ auto complete search

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#7]
Functionality that stores search terms and uses them as the basis for predictive / auto completion search. This will use Ngrams.

The search terms will need to be a new search DocType.

Need to filter out any boolean search operators such as ", AND, NOT, OR, ( etc

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/8/search-term-predictive-auto-complete

created an issue 2016-06-07

**Comment by Samyoul** [comment]
Message from @shivarora

>After checking details and task, I would require more detailed on use-case for predictive search.
>
>I need to understand what you think about predictive search in terms of predictive result relevancy algorithm and predictive search use-cases.
>
>The reason for this question ,So i can give accurate timing for completing this task.

For this feature the purpose of the predictive search functionality is to give the user an option to select the query they intend to search for before they write the entire query.

The predictive element needs to take into consideration a number of things:

* Queries that the user has entered before.
* Queries that all other users have entered before.

Because of the above the `Search Query` DocType would benefit from having a user ID, this will allow the application to search for matches based on the user's ID.

The predictive results should show specific results (matches based solely on the user's search history) and general results (matches based on the global search history). With specific results showing above the general results in the suggested queries element. 

`Search Query` matches should be weighted towards **most searched for** and **most recently searched for**. This would, hopefully, cause the query matches to give the most relevant results to the user.

**Comment by shivarora** [comment]
@Samyoul 

This explains about the relevancy. But need further information from you.

1. The predictive results should show specific results (matches based solely on the user's search history) and general results (matches based on the global search history). With specific results showing above the general results in the suggested queries element.
2. Search Query matches should be weighted towards most searched for and most recently searched for. This would, hopefully, cause the query matches to give the most relevant results to the user.

My question is:-

How they are combined together ? and what is the weight formula for most searched and recently searched?

Moreover , can  you explain a little bit about use-cases of predictive search. It will be good if can you help me with some random examples.

**Comment by Samyoul** [comment]
>How they are combined together ?

Definitions
`USH` = User Search History
`GSH` = Global Search History

I'd imagine that the searches against `USH` and `USH` are performed separately. And then use computation server side logic to parse and combine the search queries into a list to be passed to the client side.

I believe using the Google Chrome's predictive search would be a good model for the functionality that we need. On key press, take search term, return 5 predictive results. If the `USH` results return 5 or more, show the only the `USH` results. If the `USH` search returns less than 5 results perform a `GSH` search, return to the client `USH` results + ((5-`USH`) * `GSH`) results.

---

>and what is the weight formula for most searched and recently searched?

I would expect this to be something you come up with, but I will give you the process flow I have in mind.

>Moreover , can you explain a little bit about use-cases of predictive search. It will be good if can you help me with some random examples.

### Start

`Search Query` is currently "ac"

Previous searches that match the `Search Query` are:

|Search Term|Search Count|Last Searched|
|---|---|---|
|Accountant|54|2016-12-26|
|Accounts Clerk|166|2016-12-30|
|Actuary|7|2016-08-03|
|Access Manager|16|2016-07-06|
|Senior Accountant|73|2017-01-05|
|Corporate Accounts Auditor|24|2016-11-05|
|Accounts Assistant|675|2016-12-31|
|Actor|7065|2016-07-07|

_Note:_ The Ngram is compared on each word of a search term rather than on the whole term. This is why results like "Senior Accountant" and "Corporate Accounts Auditor" show in the matching results.

### Date Order and Date Chunk

We want to guess what is **currently** most popular, not what is historically popular. An idea would be to order the results by date, then break the results up into 28 day chunks.

**Chunk 1**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Senior Accountant|73|2017-01-05|
|Accounts Assistant|675|2016-12-31|
|Accounts Clerk|166|2016-12-30|
|Accountant|54|2016-12-26|

**Chunk 2**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Corporate Accounts Auditor|24|2016-11-05|

**Chunk 3**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Actuary|7|2016-08-03|

**Chunk 4**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Access Manager|16|2016-07-06|
|Actor|7065|2016-07-07|

### Count Order By Chunk, Pool First 5 Results

Then each chunk's search terms are ordered by popularity, until you have 5 results:

**Chunk 1**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Accounts Assistant|675|2016-12-31|
|Accounts Clerk|166|2016-12-30|
|Senior Accountant|73|2017-01-05|
|Accountant|54|2016-12-26|

**Chunk 2**

|Search Term|Search Count|Last Searched|
|---|---|---|
|Corporate Accounts Auditor|24|2016-11-05|

### Results to Client

After parsing and ordering the results, the data is passed to the client.

* Accounts Assistant
* Accounts Clerk
* Senior Accountant
* Accountant
* Corporate Accounts Auditor

**Comment by Samyoul** [comment]
A potential addition improvement to the above formula would be:

- Create a new field, `period search count` , this count is reset each time the same search query is made in a new chunk time period.
- Chunk per calendar month. (This has potential issues, but presently I can't see how to maintain a `period search count` without having some kind of predetermined period. A rolling period, as originally proposed, would presumably require a database table to store each search in order to get a count for any particular 28 day span)
- Order by `period search count` after date chunking

This would prevent search counts from getting unhelpfully huge.

**Comment by propulkit** [comment]
@Samyoul @shivarora 

How to handle multiple input words scenario ? For example -  if somebody types 'Clerk ac'

**Comment by Samyoul** [comment]
>How to handle multiple input words scenario ? For example - if somebody types 'Clerk ac'

I would say that each word should be handled as a separate term rather then taking the whole query as a single term.

**Comment by lifekent** [comment]
@Samyoul 
Need some clarification. 

1) Predictions keywords only saved when the CV search has given some results (Useful for skipping totally non-related search keywords).

2) `USH` are generated by users, having keywords saved with a user ID. But, to create `GSH` we need to move some keywords from the `USH` to have them available to all users - as two `USH` with different user IDs potentially can have the same phrases. - What I see as an option if the keyword was searched f.e. more than twice by the same user, we move it out of the `USH` to the `GSH` (preliminarily checking if the keyword doesn't exist), so we'll have more auto-generated suggestions for other users.

3) I think `USH` in our case makes sense to have data for the period of last ~30 days, as in case the user does search for the phrase, that is already was searched by it earlier, keyword goes to the `GSH`. With this functionality, we won't overload each `USH` which potentially can grow very fast.

Let me know if you see it different.

**Comment by Samyoul** [comment]
>Predictions keywords only saved when the CV search has given some results (Useful for skipping totally non-related search keywords).

Yes, this would be a good approach.

>USH are generated by users, having keywords saved with a user ID. But, to create GSH we need to move some keywords from the USH to have them available to all users - as two USH with different user IDs potentially can have the same phrases. - What I see as an option if the keyword was searched f.e. more than twice by the same user, we move it out of the USH to the GSH (preliminarily checking if the keyword doesn't exist), so we'll have more auto-generated suggestions for other users.

Yes this approach is fine.

>I think USH in our case makes sense to have data for the period of last ~30 days, as in case the user does search for the phrase, that is already was searched by it earlier, keyword goes to the GSH. With this functionality, we won't overload each USH which potentially can grow very fast.

How would you remove data for results older than ~30 days?

**Comment by lifekent** [comment]
The only option is to use https://www.elastic.co/guide/en/elasticsearch/reference/1.5/docs-delete-by-query.html

**Comment by Samyoul** [comment]
What I meant was how would you determine a query is older than the cut off age ( ~ 30 days ) and then delete it? Would you run a cron job to trigger a script to regularly search for old search queries and delete them?

**Comment by lifekent** [comment]
Unfortunately, this is the only option, run a cronjob (use Laravel's scheduler) that will delete `USH` items older than 30 days. Besides that, we need to have it run every minute or two, because the delete-by-query plugin quite slow and it literally removes items from the index one by one.

**Comment by Samyoul** [comment]
Ok. It's not a perfect solution, but currently I can't think of a more elegant approach. Let's proceed with what you are suggesting.

Could we have the cut off age at 45 days?

**Comment by lifekent** [comment]
Ok. I will make it 45 days

**Comment by Samyoul** [comment]
Thanks for your work, I have some issues:

**Default browser suggestion:**

We need to disable the browser's auto suggestion option.

![screenshot 2017-03-21 11 17 58](https://cloud.githubusercontent.com/assets/5702426/24145270/51053320-0e28-11e7-93cf-71e656b2f847.png)

**Multiple Entry Bug:**

If you enter a keyword multiple times, instead of handling the keyword as mentioned here https://github.com/Samyoul/dywaj-issues/issues/7#issuecomment-270698734 , with highest frequency search terms going to the top, currently the suggested items are ordered by date created and show the same search terms multiple times.

![cv search submit](https://cloud.githubusercontent.com/assets/5702426/24145331/a2fd14a4-0e28-11e7-9213-9f39b62a73a9.png)

**Comment by lifekent** [comment]
Multiple Entry Bug - that's my today's fault, I have just removed it while adding a check by ID and didn't add it to commit back. I will let you know when I will push all the updates.

**Comment by lifekent** [comment]
@Samyoul I have pushed updates. Sorry for the delay.

**Comment by lifekent** [comment]
I have also removed all previous predictions from the index so you can start from scratch.

**Comment by Samyoul** [comment]
Thank you. Everything seems to be working as it should. Please make the pull request.

**Comment by Samyoul** [comment]
https://github.com/Samyoul/dywaj-user-interface/pull/18
