### ISSUE TITLE
Password Change Functionality

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#71]
Currently there is no way to change passwords. We need to Add it.

**Comment by Nyanko-sensei** [comment]
If user changes his password, should we send email with notification that password was changed and link "If you didn't change password click there" which would cancel previous password change and redirect user to password change view?

**Comment by Samyoul** [comment]
Yes. Feel free to add that functionality.

Will we create new database field for the old password?

**Comment by Nyanko-sensei** [comment]
Did first part (Password Change Functionality)
Tomorrow  will do second part ( Password reset email ) And yes, for that i'll need to create migration to add old_password, reset_token, reset_token_expire_date fields.
pull request for first part:
https://github.com/Samyoul/dywaj-user-interface/pull/30

**Comment by Samyoul** [comment]
Will you be integrating the files from `php artisan auth:make` ?

**Comment by Samyoul** [comment]
I'll re-assign https://github.com/Samyoul/dywaj-issues/issues/56 to you because this issue specifically deals with forgotten password functionality.
