### ISSUE TITLE
Distance in miles drop down of pre-set numbers

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#8]
Distance in miles drop down of pre-set numbers, with an advanced, but hidden, option for entering a specific floating point number.

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/9/distance-in-miles-drop-down-of-pre-set

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul what would be the pre-set numbers options? What should be the default?

What do you mean "hidden"? Like input hidden field?

**Comment by Samyoul** [comment]
>@Samyoul what would be the pre-set numbers options? What should be the default?

Preset numbers : 1, 2, 3, 4, 5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 250, 300, 400, 500

>What do you mean "hidden"? Like input hidden field?

Please reference https://github.com/Samyoul/dywaj-issues/issues/12#issuecomment-280709422 . I mean in  a div element that has a style of `display:none;` that can be revealed by clicking on an "advanced search" link, triggering a JavaScript event the animates the hidden div into view. http://api.jquery.com/slidedown/
