### ISSUE TITLE
Truncate the postcode in the results to remove the last 3 Chars

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#9]
From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/10/truncate-the-postcode-in-the-results-to

created an issue 2016-06-08

**Comment by PovilasKorop** [comment]
@Samyoul you mean for example E10 5PJ should become E10? What if a person enters postcode like London's WC1A, removing last 3 chars will only leave W.

**Comment by Samyoul** [comment]
For reference the view code ( https://github.com/Samyoul/dywaj-user-interface/blob/master/resources/views/cv-search/result.blade.php#L37 ) .

The search engine always takes a full postcode as an input and will always return a full UK postcode, so when truncating the last three chars the application won't need to deal with the edge case you highlight.
